# Generated by Django 3.1.7 on 2021-12-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211220_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_por_cobrar',
            name='id_sist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sistemas'),
        ),
    ]
