# Generated by Django 3.1.7 on 2021-12-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211220_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemas',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
